apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jc5vof0u1-nodejs-gitops
  description: This is GitOps manifest for jc5vof0u1-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=jc5vof0u1-nodejs
    backstage.io/kubernetes-id: jc5vof0u1-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jc5vof0u1-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jc5vof0u1-nodejs
